//
//  BlogPosts.swift
//  blogdeneme
//
//  Created by Eda Gencay on 16.05.2024.
//

import Foundation
struct BlogPosts : Identifiable {
      
    var id : Int
    var name : String
    var image : String
    var details : String
    
}
  
var latestpost = [
  
    BlogPosts(id: 0, name: "Karbon Ayak İzi Nedir?", image: "0", details: "Karbon ayak izi, bir kişi, bir kuruluş, bir ürün veya bir etkinlik tarafından atmosfere salınan sera gazı emisyonlarının miktarını ölçen bir terimdir. Bu emisyonlar genellikle karbondioksit (CO2), metan (CH4), azot oksitler (NOx) ve diğer sera gazlarını içerir.Karbon ayak izi, bir varlığın veya etkinliğin çevreye olan etkisini ölçmekte kullanılır. Örneğin, bir kişinin günlük yaşamında kullandığı enerji, ulaşım araçlarını kullandığı yakıtlar, yiyecek tüketimi ve yaşam tarzı, karbon ayak izini oluşturur. Benzer şekilde, bir şirketin ürettiği ürünlerin imalatı, dağıtımı ve son kullanıcıya ulaştırılması sırasında oluşan sera gazı emisyonları da karbon ayak izini oluşturur.Karbon ayak izi ölçümü, çevresel etkinin farkında olmayı ve sera gazı emisyonlarını azaltmayı teşvik eder. Bir kişi veya kuruluşun karbon ayak izini azaltmak için yapabileceği eylemler arasında enerji verimliliğini artırmak, yenilenebilir enerji kaynaklarına geçmek, ulaşımı paylaşmak veya elektrikli araçlar kullanmak, sera gazı emisyonlarını azaltan ürünler ve hizmetler satın almak ve sera gazı emisyonlarını telafi etmek gibi adımlar bulunur."),
    BlogPosts(id: 1, name: "Karbon Ayak İzimizi Nasıl Azaltabiliriz?", image: "1", details: "Günümüzde iklim değişikliği ve çevre sorunları, karbon ayak izimizi azaltmanın önemini daha da belirgin hale getirdi. Bireysel ve toplumsal çabalarla, enerji tasarrufu yaparak, toplu taşıma ve bisiklet kullanarak, geri dönüşüm ve atık yönetimi uygulayarak, yerel ve mevsimsel ürünler tüketerek, tüketim alışkanlıklarımızı gözden geçirerek ve doğa dostu ürünler kullanarak karbon emisyonlarımızı azaltabiliriz. Enerji verimli ampuller, yürüyüş ve bisiklet, geri dönüşüm, yerel gıda tüketimi, minimalizm ve sürdürülebilir ürün tercihleri, atılacak önemli adımlardan sadece birkaçıdır. Küçük değişikliklerle büyük farklar yaratabileceğimiz bu süreçte, gezegenimizi korumak bizim elimizde."),
    BlogPosts(id: 2, name: "Atık Yönetimi ve Atık Ayrıştırma", image: "2", details: "Atık yönetimi ve atık ayrıştırma, çevreyi koruma ve sürdürülebilir bir gelecek sağlama açısından büyük önem taşır. Atıkların kaynağında ayrıştırılması, geri dönüşüm süreçlerini kolaylaştırır ve doğal kaynakların korunmasına yardımcı olur. Organik atıklar kompost yapılarak geri dönüştürülebilirken, plastik, cam, metal ve kağıt gibi malzemeler ayrı ayrı toplanarak yeniden işlenebilir. Etkili atık yönetimi, enerji tasarrufu sağlar ve çöp sahalarındaki atık miktarını azaltarak sera gazı emisyonlarını düşürür. Bu nedenle, bireylerin ve toplumların atık ayrıştırma konusunda bilinçlenmesi ve aktif olarak katılım sağlaması gereklidir."),
    BlogPosts(id: 3, name: "Dünya Emisyon Oranları", image: "dünya", details: "Dünya emisyon oranları, ülkeler ve sektörler arasında büyük farklılıklar gösteren, iklim değişikliğinin ana nedenlerinden biri olan sera gazı salınımlarını ifade eder. En büyük emisyon kaynakları arasında enerji üretimi, ulaşım, sanayi ve tarım yer almaktadır. Çin, Amerika Birleşik Devletleri, Avrupa Birliği ve Hindistan, toplam küresel emisyonların büyük bir kısmını oluşturan başlıca salıcı ülkeler arasındadır. Fosil yakıtların yakılması, özellikle kömür, petrol ve doğalgaz kullanımı, bu emisyonların en büyük kaynağını teşkil ederken, ormansızlaşma ve tarım faaliyetleri de önemli katkılar sağlamaktadır. Küresel emisyon oranlarının azaltılması için yenilenebilir enerji kaynaklarına geçiş, enerji verimliliğinin artırılması, sürdürülebilir tarım uygulamaları ve ormanların korunması gibi önlemler gerekmektedir. Paris Anlaşması kapsamında, ülkeler belirli emisyon azaltım hedefleri koyarak bu küresel sorunun çözümüne katkıda bulunmayı taahhüt etmektedir."),
    BlogPosts(id: 4, name: "Sıfır Atık Nedir?", image: "4", details: "Sıfır atık, atık oluşumunu en aza indirmeyi ve atıkları yeniden kullanarak, geri dönüştürerek veya kompost yaparak doğal döngüye kazandırmayı amaçlayan sürdürülebilir bir yaşam biçimidir. Bu yaklaşım, üretim ve tüketim süreçlerinde kaynakları daha verimli kullanarak atık miktarını azaltmayı ve çevre üzerindeki olumsuz etkileri en aza indirmeyi hedefler. Sıfır atık felsefesi, sadece bireysel çabaları değil, aynı zamanda toplumsal ve endüstriyel düzeyde de değişiklikleri içerir, böylece doğanın korunmasına ve ekolojik dengeye önemli katkılar sağlar."),
    BlogPosts(id: 5, name: "Elektrikte Yeşil Tarife Nedir?", image: "5", details: "Elektrikte yeşil tarife, enerji tüketicilerinin elektrik ihtiyaçlarını yenilenebilir enerji kaynaklarından karşılamasını sağlayan bir tarifedir. Bu tarife, rüzgar, güneş, hidroelektrik ve biyokütle gibi çevre dostu ve sürdürülebilir enerji kaynaklarından üretilen elektriği kapsar. Yeşil tarife ile kullanıcılar, fosil yakıtlardan elde edilen elektriğin yerine temiz enerji kullanarak karbon ayak izlerini azaltabilir ve çevreye olan olumsuz etkilerini en aza indirebilirler. Bu, hem bireyler hem de işletmeler için doğa dostu bir seçenek sunarak, yenilenebilir enerji sektörünün gelişmesine de katkı sağlar."),
    BlogPosts(id: 6, name: "Türkiye'nin Sera Gazı Salınımı ve Azaltım Politikaları", image: "türkiye", details: "Türkiye'nin sera gazı salınımı, sanayi, enerji, ulaşım ve tarım gibi sektörlerden kaynaklanmaktadır. Ülke, iklim değişikliğiyle mücadele ve Paris Anlaşması hedeflerine ulaşmak için çeşitli azaltım politikaları benimsemiştir. Bu politikalar arasında yenilenebilir enerji kaynaklarının kullanımının artırılması, enerji verimliliğinin teşvik edilmesi ve karbon emisyonlarının izlenmesi yer almaktadır. Türkiye, 2030 yılına kadar sera gazı emisyonlarını %21 oranında azaltma hedefi belirlemiş olup, bu doğrultuda yenilenebilir enerji projeleri ve enerji verimliliği yatırımlarını desteklemekte, ayrıca ormanlaştırma ve sürdürülebilir tarım uygulamalarını teşvik etmektedir. Bu çabalar, Türkiye'nin karbon ayak izini azaltarak iklim değişikliğiyle mücadelede daha etkin bir rol oynamasını amaçlamaktadır."),
    BlogPosts(id: 7, name: "E-Atık Nedir?", image: "7", details: "E-atık, kullanımı sona ermiş veya işlevini yitirmiş elektronik cihazların ve bileşenlerin oluşturduğu atıklardır. Bu atıklar, bilgisayarlar, cep telefonları, televizyonlar, yazıcılar gibi elektronik ürünleri içerir. E-atık, genellikle tehlikeli maddeler içerdiği için doğru şekilde yönetilmezse çevre ve insan sağlığı üzerinde olumsuz etkiler yaratabilir. Bu nedenle, e-atıkların geri dönüşüm ve yeniden kullanım süreçlerine dahil edilmesi, doğal kaynakların korunmasına ve çevre kirliliğinin önlenmesine önemli katkılar sağlar."),
]
 
var featuredpost = [
  
    BlogPosts(id: 0, name: "Karbon Ayak İzi Nedir?", image: "0", details: "Karbon ayak izi, bir kişi, bir kuruluş, bir ürün veya bir etkinlik tarafından atmosfere salınan sera gazı emisyonlarının miktarını ölçen bir terimdir. Bu emisyonlar genellikle karbondioksit (CO2), metan (CH4), azot oksitler (NOx) ve diğer sera gazlarını içerir.Karbon ayak izi, bir varlığın veya etkinliğin çevreye olan etkisini ölçmekte kullanılır. Örneğin, bir kişinin günlük yaşamında kullandığı enerji, ulaşım araçlarını kullandığı yakıtlar, yiyecek tüketimi ve yaşam tarzı, karbon ayak izini oluşturur. Benzer şekilde, bir şirketin ürettiği ürünlerin imalatı, dağıtımı ve son kullanıcıya ulaştırılması sırasında oluşan sera gazı emisyonları da karbon ayak izini oluşturur.Karbon ayak izi ölçümü, çevresel etkinin farkında olmayı ve sera gazı emisyonlarını azaltmayı teşvik eder. Bir kişi veya kuruluşun karbon ayak izini azaltmak için yapabileceği eylemler arasında enerji verimliliğini artırmak, yenilenebilir enerji kaynaklarına geçmek, ulaşımı paylaşmak veya elektrikli araçlar kullanmak, sera gazı emisyonlarını azaltan ürünler ve hizmetler satın almak ve sera gazı emisyonlarını telafi etmek gibi adımlar bulunur."),
    BlogPosts(id: 1, name: "Karbon Ayak İzimizi Nasıl Azaltabiliriz?", image: "1", details: "Günümüzde iklim değişikliği ve çevre sorunları, karbon ayak izimizi azaltmanın önemini daha da belirgin hale getirdi. Bireysel ve toplumsal çabalarla, enerji tasarrufu yaparak, toplu taşıma ve bisiklet kullanarak, geri dönüşüm ve atık yönetimi uygulayarak, yerel ve mevsimsel ürünler tüketerek, tüketim alışkanlıklarımızı gözden geçirerek ve doğa dostu ürünler kullanarak karbon emisyonlarımızı azaltabiliriz. Enerji verimli ampuller, yürüyüş ve bisiklet, geri dönüşüm, yerel gıda tüketimi, minimalizm ve sürdürülebilir ürün tercihleri, atılacak önemli adımlardan sadece birkaçıdır. Küçük değişikliklerle büyük farklar yaratabileceğimiz bu süreçte, gezegenimizi korumak bizim elimizde."),
]
